---
- name: Copy tmpfiles.d config
  template:
    src: ./templates/tmpfiles.config.j2
    dest: "/usr/lib/tmpfiles.d/twitcher.conf"
  tags:
    - twitcher
    - conf

- name: Copy twitcher config
  template:
    src: ./templates/twitcher.ini.j2
    dest: "{{ twitcher_ini }}"
  tags:
    - twitcher
    - conf
