---
- include: source.yml

- include: conda.yml

- include: folders.yml

- include: config.yml

- include: db.yml

- include: sqlite.yml
  when: db_install_sqlite

- include: supervisor.yml

- include: certs.yml

- include: nginx.yml

- name: Assure Twitcher running at end of playbook
  command: /bin/true
  notify:
    - restart twitcher
  tags:
    - twitcher
    - conf

- name: Assure nginx running at end of playbook
  command: /bin/true
  notify:
    - restart nginx
  tags:
    - nginx
    - conf
