- name: Install common packages on RedHat
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - gcc-c++
      - make
      - libselinux-python
      - initscripts
      - python-meld3
      - openssl-devel

- name: Remove unwanted packages on RedHat
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - supervisor
